// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfTUvXlP_L0yiPfpkf_hqDDQJ1WkcYZcU',
    appId: '1:790922899145:web:c7671c9bcccfae41b5e718',
    messagingSenderId: '790922899145',
    projectId: 'buddy-link-at',
    authDomain: 'buddy-link-at.firebaseapp.com',
    storageBucket: 'buddy-link-at.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALuIGgEvh_h7GfcG1yuYhsJvBAPjmlYWk',
    appId: '1:790922899145:android:13f44e55e4adadcfb5e718',
    messagingSenderId: '790922899145',
    projectId: 'buddy-link-at',
    storageBucket: 'buddy-link-at.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi767XmkBSsN98BMvB-ZvZjxOIjUMRPdg',
    appId: '1:790922899145:ios:d79e7af9a6926bdbb5e718',
    messagingSenderId: '790922899145',
    projectId: 'buddy-link-at',
    storageBucket: 'buddy-link-at.appspot.com',
    iosClientId: '790922899145-od1prt5b2jsfsu1aerdd1pkkv2l7i9a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddylink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi767XmkBSsN98BMvB-ZvZjxOIjUMRPdg',
    appId: '1:790922899145:ios:d79e7af9a6926bdbb5e718',
    messagingSenderId: '790922899145',
    projectId: 'buddy-link-at',
    storageBucket: 'buddy-link-at.appspot.com',
    iosClientId: '790922899145-od1prt5b2jsfsu1aerdd1pkkv2l7i9a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buddylink',
  );
}
